// Generated by gencpp from file ras_service/AddTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef RAS_SERVICE_MESSAGE_ADDTWOINTSRESPONSE_H
#define RAS_SERVICE_MESSAGE_ADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ras_service
{
template <class ContainerAllocator>
struct AddTwoIntsResponse_
{
  typedef AddTwoIntsResponse_<ContainerAllocator> Type;

  AddTwoIntsResponse_()
    : suma(0)  {
    }
  AddTwoIntsResponse_(const ContainerAllocator& _alloc)
    : suma(0)  {
  (void)_alloc;
    }



   typedef int64_t _suma_type;
  _suma_type suma;





  typedef boost::shared_ptr< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsResponse_

typedef ::ras_service::AddTwoIntsResponse_<std::allocator<void> > AddTwoIntsResponse;

typedef boost::shared_ptr< ::ras_service::AddTwoIntsResponse > AddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::ras_service::AddTwoIntsResponse const> AddTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ras_service::AddTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ras_service::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::ras_service::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.suma == rhs.suma;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ras_service::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::ras_service::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ras_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51c6be16de0582cf6eb0cd86b87dd80d";
  }

  static const char* value(const ::ras_service::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51c6be16de0582cfULL;
  static const uint64_t static_value2 = 0x6eb0cd86b87dd80dULL;
};

template<class ContainerAllocator>
struct DataType< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ras_service/AddTwoIntsResponse";
  }

  static const char* value(const ::ras_service::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 suma\n"
;
  }

  static const char* value(const ::ras_service::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.suma);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ras_service::AddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ras_service::AddTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "suma: ";
    Printer<int64_t>::stream(s, indent + "  ", v.suma);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAS_SERVICE_MESSAGE_ADDTWOINTSRESPONSE_H
