// Generated by gencpp from file robot_arm_controller/AnglesConverter.msg
// DO NOT EDIT!


#ifndef ROBOT_ARM_CONTROLLER_MESSAGE_ANGLESCONVERTER_H
#define ROBOT_ARM_CONTROLLER_MESSAGE_ANGLESCONVERTER_H

#include <ros/service_traits.h>


#include <robot_arm_controller/AnglesConverterRequest.h>
#include <robot_arm_controller/AnglesConverterResponse.h>


namespace robot_arm_controller
{

struct AnglesConverter
{

typedef AnglesConverterRequest Request;
typedef AnglesConverterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnglesConverter
} // namespace robot_arm_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_arm_controller::AnglesConverter > {
  static const char* value()
  {
    return "904e8346ace63ec441f6f58d8efc6687";
  }

  static const char* value(const ::robot_arm_controller::AnglesConverter&) { return value(); }
};

template<>
struct DataType< ::robot_arm_controller::AnglesConverter > {
  static const char* value()
  {
    return "robot_arm_controller/AnglesConverter";
  }

  static const char* value(const ::robot_arm_controller::AnglesConverter&) { return value(); }
};


// service_traits::MD5Sum< ::robot_arm_controller::AnglesConverterRequest> should match
// service_traits::MD5Sum< ::robot_arm_controller::AnglesConverter >
template<>
struct MD5Sum< ::robot_arm_controller::AnglesConverterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_arm_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robot_arm_controller::AnglesConverterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_arm_controller::AnglesConverterRequest> should match
// service_traits::DataType< ::robot_arm_controller::AnglesConverter >
template<>
struct DataType< ::robot_arm_controller::AnglesConverterRequest>
{
  static const char* value()
  {
    return DataType< ::robot_arm_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robot_arm_controller::AnglesConverterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_arm_controller::AnglesConverterResponse> should match
// service_traits::MD5Sum< ::robot_arm_controller::AnglesConverter >
template<>
struct MD5Sum< ::robot_arm_controller::AnglesConverterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_arm_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robot_arm_controller::AnglesConverterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_arm_controller::AnglesConverterResponse> should match
// service_traits::DataType< ::robot_arm_controller::AnglesConverter >
template<>
struct DataType< ::robot_arm_controller::AnglesConverterResponse>
{
  static const char* value()
  {
    return DataType< ::robot_arm_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robot_arm_controller::AnglesConverterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_ARM_CONTROLLER_MESSAGE_ANGLESCONVERTER_H
