// Generated by gencpp from file robot_arm_remote/robotarmTaskFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_ARM_REMOTE_MESSAGE_ROBOTARMTASKFEEDBACK_H
#define ROBOT_ARM_REMOTE_MESSAGE_ROBOTARMTASKFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_arm_remote
{
template <class ContainerAllocator>
struct robotarmTaskFeedback_
{
  typedef robotarmTaskFeedback_<ContainerAllocator> Type;

  robotarmTaskFeedback_()
    : percentage(0)  {
    }
  robotarmTaskFeedback_(const ContainerAllocator& _alloc)
    : percentage(0)  {
  (void)_alloc;
    }



   typedef int64_t _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct robotarmTaskFeedback_

typedef ::robot_arm_remote::robotarmTaskFeedback_<std::allocator<void> > robotarmTaskFeedback;

typedef boost::shared_ptr< ::robot_arm_remote::robotarmTaskFeedback > robotarmTaskFeedbackPtr;
typedef boost::shared_ptr< ::robot_arm_remote::robotarmTaskFeedback const> robotarmTaskFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator1> & lhs, const ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator1> & lhs, const ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_arm_remote

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face31f38d20abbde445df7aa912bb07";
  }

  static const char* value(const ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xface31f38d20abbdULL;
  static const uint64_t static_value2 = 0xe445df7aa912bb07ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_arm_remote/robotarmTaskFeedback";
  }

  static const char* value(const ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"int64 percentage\n"
;
  }

  static const char* value(const ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotarmTaskFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_arm_remote::robotarmTaskFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<int64_t>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_ARM_REMOTE_MESSAGE_ROBOTARMTASKFEEDBACK_H
