; Auto-generated. Do not edit!


(cl:in-package robot_arm_remote-msg)


;//! \htmlinclude robotarmTaskFeedback.msg.html

(cl:defclass <robotarmTaskFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage
    :reader percentage
    :initarg :percentage
    :type cl:integer
    :initform 0))
)

(cl:defclass robotarmTaskFeedback (<robotarmTaskFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robotarmTaskFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robotarmTaskFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_arm_remote-msg:<robotarmTaskFeedback> is deprecated: use robot_arm_remote-msg:robotarmTaskFeedback instead.")))

(cl:ensure-generic-function 'percentage-val :lambda-list '(m))
(cl:defmethod percentage-val ((m <robotarmTaskFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_arm_remote-msg:percentage-val is deprecated.  Use robot_arm_remote-msg:percentage instead.")
  (percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robotarmTaskFeedback>) ostream)
  "Serializes a message object of type '<robotarmTaskFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'percentage)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robotarmTaskFeedback>) istream)
  "Deserializes a message object of type '<robotarmTaskFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'percentage) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robotarmTaskFeedback>)))
  "Returns string type for a message object of type '<robotarmTaskFeedback>"
  "robot_arm_remote/robotarmTaskFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robotarmTaskFeedback)))
  "Returns string type for a message object of type 'robotarmTaskFeedback"
  "robot_arm_remote/robotarmTaskFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robotarmTaskFeedback>)))
  "Returns md5sum for a message object of type '<robotarmTaskFeedback>"
  "face31f38d20abbde445df7aa912bb07")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robotarmTaskFeedback)))
  "Returns md5sum for a message object of type 'robotarmTaskFeedback"
  "face31f38d20abbde445df7aa912bb07")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robotarmTaskFeedback>)))
  "Returns full string definition for message of type '<robotarmTaskFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int64 percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robotarmTaskFeedback)))
  "Returns full string definition for message of type 'robotarmTaskFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int64 percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robotarmTaskFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robotarmTaskFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'robotarmTaskFeedback
    (cl:cons ':percentage (percentage msg))
))
